/**
 * 
 */
package client.controller;

/**
 * @author Monera
 * This enum specifies the type of controllers 
 */
public enum ControllerType {

	LOGIN_CONTROLLER,
	REGISTRATION_CONTROLLER,
	
	//USER_SEARCH_BOOKS_CONTROLLER,

	
	USER_HOME_CONTROLLER,
	READER_HOME_CONTROLLER,
	LIBRARIAN_HOME_CONTROLLER,
	MANAGER_HOME_CONTROLLER,
	
	BOOKS_CONTROLLER,
	
	ADD_BOOK_CONTROLLER, //Rania
	
	DELETE_BOOK_CONTROLLER, //Rania
	
	ORDER_BOOK_CONTROLLER,//Karam
	
	RETURN_BOOK_CONTROLLER,//shams
	REGISTRATION_CONTROLER,//shams
	
	BORROW_FORM_CONTROLLER,
	
	READER_INFO_CONTROLLER,//shams
	EMPLOYEE_INFO_CONTROLLER,//shams
	
 EDIT_BOOK_CONTROLLER,//Rania 
	
 HISTORY_CONTROLLER,
 
 LIBRARIAN_DEADLINE_EXTENSION,
	DEADLINE_EXTENSION,
 
	MY_LIBRARY_CARD_CONTROLLER,
	SHOW_BORROWED_BOOKS_CONTROLLER, //Karam
	REPORTS_CONTROLLER,//SHAMS&KARAM
BORROW_FREEZE_CONTROLLER,
	
	THREE_LATE_RETURNS_CONTROLLER,
	
	VIEW_TOC_CONTROLLER;
	
}